export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
  
export default function RootLayout({ children }) {
 return (
  
    <html lang="en">
 

      <body>{children}
      
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossOrigin="anonymous"></script>
      </body>
    </html>
  )
}
